/* tslint:disable */
/* eslint-disable */
/**
 * Noodle
 * Noodle
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Application } from './Application';
import {
    ApplicationFromJSON,
    ApplicationFromJSONTyped,
    ApplicationToJSON,
} from './Application';

/**
 * 
 * @export
 * @interface ApplicationTab
 */
export interface ApplicationTab {
    /**
     * 
     * @type {number}
     * @memberof ApplicationTab
     */
    Id?: number;
    /**
     * 
     * @type {number}
     * @memberof ApplicationTab
     */
    ApplicationId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApplicationTab
     */
    TabId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApplicationTab
     */
    DisplayOrder?: number;
    /**
     * 
     * @type {Application}
     * @memberof ApplicationTab
     */
    Application?: Application;
}

/**
 * Check if a given object implements the ApplicationTab interface.
 */
export function instanceOfApplicationTab(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApplicationTabFromJSON(json: any): ApplicationTab {
    return ApplicationTabFromJSONTyped(json, false);
}

export function ApplicationTabFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationTab {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Id': !exists(json, 'Id') ? undefined : json['Id'],
        'ApplicationId': !exists(json, 'ApplicationId') ? undefined : json['ApplicationId'],
        'TabId': !exists(json, 'TabId') ? undefined : json['TabId'],
        'DisplayOrder': !exists(json, 'DisplayOrder') ? undefined : json['DisplayOrder'],
        'Application': !exists(json, 'Application') ? undefined : ApplicationFromJSON(json['Application']),
    };
}

export function ApplicationTabToJSON(value?: ApplicationTab | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.Id,
        'ApplicationId': value.ApplicationId,
        'TabId': value.TabId,
        'DisplayOrder': value.DisplayOrder,
        'Application': ApplicationToJSON(value.Application),
    };
}

