/* tslint:disable */
/* eslint-disable */
/**
 * Noodle
 * Noodle
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Application
 */
export interface Application {
    /**
     * 
     * @type {number}
     * @memberof Application
     */
    Id?: number;
    /**
     * 
     * @type {string}
     * @memberof Application
     */
    TemplateAppid?: string;
    /**
     * 
     * @type {string}
     * @memberof Application
     */
    Name?: string;
    /**
     * 
     * @type {string}
     * @memberof Application
     */
    Website?: string;
    /**
     * 
     * @type {string}
     * @memberof Application
     */
    License?: string;
    /**
     * 
     * @type {string}
     * @memberof Application
     */
    Description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Application
     */
    Enhanced?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Application
     */
    TileBackground?: string;
    /**
     * 
     * @type {string}
     * @memberof Application
     */
    Icon?: string;
}

/**
 * Check if a given object implements the Application interface.
 */
export function instanceOfApplication(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApplicationFromJSON(json: any): Application {
    return ApplicationFromJSONTyped(json, false);
}

export function ApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Application {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Id': !exists(json, 'Id') ? undefined : json['Id'],
        'TemplateAppid': !exists(json, 'TemplateAppid') ? undefined : json['TemplateAppid'],
        'Name': !exists(json, 'Name') ? undefined : json['Name'],
        'Website': !exists(json, 'Website') ? undefined : json['Website'],
        'License': !exists(json, 'License') ? undefined : json['License'],
        'Description': !exists(json, 'Description') ? undefined : json['Description'],
        'Enhanced': !exists(json, 'Enhanced') ? undefined : json['Enhanced'],
        'TileBackground': !exists(json, 'TileBackground') ? undefined : json['TileBackground'],
        'Icon': !exists(json, 'Icon') ? undefined : json['Icon'],
    };
}

export function ApplicationToJSON(value?: Application | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.Id,
        'TemplateAppid': value.TemplateAppid,
        'Name': value.Name,
        'Website': value.Website,
        'License': value.License,
        'Description': value.Description,
        'Enhanced': value.Enhanced,
        'TileBackground': value.TileBackground,
        'Icon': value.Icon,
    };
}

