/* tslint:disable */
/* eslint-disable */
/**
 * Noodle
 * Noodle
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Application } from './Application';
import {
    ApplicationFromJSON,
    ApplicationFromJSONTyped,
    ApplicationToJSON,
} from './Application';

/**
 * 
 * @export
 * @interface GroupApplications
 */
export interface GroupApplications {
    /**
     * 
     * @type {number}
     * @memberof GroupApplications
     */
    Id?: number;
    /**
     * 
     * @type {number}
     * @memberof GroupApplications
     */
    ApplicationId?: number;
    /**
     * 
     * @type {number}
     * @memberof GroupApplications
     */
    GroupId?: number;
    /**
     * 
     * @type {Application}
     * @memberof GroupApplications
     */
    Application?: Application;
}

/**
 * Check if a given object implements the GroupApplications interface.
 */
export function instanceOfGroupApplications(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GroupApplicationsFromJSON(json: any): GroupApplications {
    return GroupApplicationsFromJSONTyped(json, false);
}

export function GroupApplicationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupApplications {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Id': !exists(json, 'Id') ? undefined : json['Id'],
        'ApplicationId': !exists(json, 'ApplicationId') ? undefined : json['ApplicationId'],
        'GroupId': !exists(json, 'GroupId') ? undefined : json['GroupId'],
        'Application': !exists(json, 'Application') ? undefined : ApplicationFromJSON(json['Application']),
    };
}

export function GroupApplicationsToJSON(value?: GroupApplications | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.Id,
        'ApplicationId': value.ApplicationId,
        'GroupId': value.GroupId,
        'Application': ApplicationToJSON(value.Application),
    };
}

