/* tslint:disable */
/* eslint-disable */
/**
 * Noodle
 * Noodle
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ModelError
 */
export interface ModelError {
  /**
   *
   * @type {number}
   * @memberof ModelError
   */
  Code?: number;
  /**
   *
   * @type {string}
   * @memberof ModelError
   */
  Message?: string;
  /**
   *
   * @type {string}
   * @memberof ModelError
   */
  Fields?: string;
}

/**
 * Check if a given object implements the ModelError interface.
 */
export function instanceOfModelError(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ModelErrorFromJSON(json: any): ModelError {
  return ModelErrorFromJSONTyped(json, false);
}

export function ModelErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ModelError {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    Code: !exists(json, 'code') ? undefined : json['code'],
    Message: !exists(json, 'message') ? undefined : json['message'],
    Fields: !exists(json, 'fields') ? undefined : json['fields'],
  };
}

export function ModelErrorToJSON(value?: ModelError | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    code: value.Code,
    message: value.Message,
    fields: value.Fields,
  };
}
