/* tslint:disable */
/* eslint-disable */
/**
 * Noodle
 * Noodle
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Tab
 */
export interface Tab {
  /**
   *
   * @type {number}
   * @memberof Tab
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof Tab
   */
  label?: string;
  /**
   *
   * @type {number}
   * @memberof Tab
   */
  displayOrder?: number;
}

/**
 * Check if a given object implements the Tab interface.
 */
export function instanceOfTab(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function TabFromJSON(json: any): Tab {
  return TabFromJSONTyped(json, false);
}

export function TabFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tab {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'Id') ? undefined : json['Id'],
    label: !exists(json, 'Label') ? undefined : json['Label'],
    displayOrder: !exists(json, 'DisplayOrder')
      ? undefined
      : json['DisplayOrder'],
  };
}

export function TabToJSON(value?: Tab | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    Id: value.id,
    Label: value.label,
    DisplayOrder: value.displayOrder,
  };
}
