/* tslint:disable */
/* eslint-disable */
/**
 * Noodle
 * Noodle
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Application } from './Application';
import {
  ApplicationFromJSON,
  ApplicationFromJSONTyped,
  ApplicationToJSON,
} from './Application';

/**
 *
 * @export
 * @interface UsersApplicationItem
 */
export interface UsersApplicationItem {
  /**
   *
   * @type {number}
   * @memberof UsersApplicationItem
   */
  TabId?: number;
  /**
   *
   * @type {number}
   * @memberof UsersApplicationItem
   */
  DisplayOrder?: number;
  /**
   *
   * @type {Application}
   * @memberof UsersApplicationItem
   */
  Application?: Application;
}

/**
 * Check if a given object implements the UsersApplicationItem interface.
 */
export function instanceOfUsersApplicationItem(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UsersApplicationItemFromJSON(json: any): UsersApplicationItem {
  return UsersApplicationItemFromJSONTyped(json, false);
}

export function UsersApplicationItemFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersApplicationItem {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    TabId: !exists(json, 'TabId') ? undefined : json['TabId'],
    DisplayOrder: !exists(json, 'DisplayOrder')
      ? undefined
      : json['DisplayOrder'],
    Application: !exists(json, 'Application')
      ? undefined
      : ApplicationFromJSON(json['Application']),
  };
}

export function UsersApplicationItemToJSON(
  value?: UsersApplicationItem | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    TabId: value.TabId,
    DisplayOrder: value.DisplayOrder,
    Application: ApplicationToJSON(value.Application),
  };
}
