/* tslint:disable */
/* eslint-disable */
/**
 * Noodle
 * Noodle
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   *
   * @type {number}
   * @memberof User
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof User
   */
  username?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  dN?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  displayName?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  givenName?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  surname?: string;
  /**
   *
   * @type {number}
   * @memberof User
   */
  uidNumber?: number;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UserFromJSON(json: any): User {
  return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): User {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'Id') ? undefined : json['Id'],
    username: !exists(json, 'Username') ? undefined : json['Username'],
    dN: !exists(json, 'DN') ? undefined : json['DN'],
    displayName: !exists(json, 'DisplayName') ? undefined : json['DisplayName'],
    givenName: !exists(json, 'GivenName') ? undefined : json['GivenName'],
    surname: !exists(json, 'Surname') ? undefined : json['Surname'],
    uidNumber: !exists(json, 'UidNumber') ? undefined : json['UidNumber'],
  };
}

export function UserToJSON(value?: User | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    Id: value.id,
    Username: value.username,
    DN: value.dN,
    DisplayName: value.displayName,
    GivenName: value.givenName,
    Surname: value.surname,
    UidNumber: value.uidNumber,
  };
}
