targets:
  $default:
    sources:
      - lib/**
      - swagger/**
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'swagger/'
          output_folder: 'lib/swagger_generated'
          seperate_models: true
          default_header_values_map:
            - header_name: "Access-Control-Allow-Origin"
              header_value: "*"