// Code generated by go-swagger; DO NOT EDIT.

package noodle_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/mwinters-stuff/noodle/server/models"
)

// DeleteNoodleTabsHandlerFunc turns a function with the right signature into a delete noodle tabs handler
type DeleteNoodleTabsHandlerFunc func(DeleteNoodleTabsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteNoodleTabsHandlerFunc) Handle(params DeleteNoodleTabsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteNoodleTabsHandler interface for that can handle valid delete noodle tabs params
type DeleteNoodleTabsHandler interface {
	Handle(DeleteNoodleTabsParams, *models.Principal) middleware.Responder
}

// NewDeleteNoodleTabs creates a new http.Handler for the delete noodle tabs operation
func NewDeleteNoodleTabs(ctx *middleware.Context, handler DeleteNoodleTabsHandler) *DeleteNoodleTabs {
	return &DeleteNoodleTabs{Context: ctx, Handler: handler}
}

/*
	DeleteNoodleTabs swagger:route DELETE /noodle/tabs noodle-api deleteNoodleTabs

Deletes the tab
*/
type DeleteNoodleTabs struct {
	Context *middleware.Context
	Handler DeleteNoodleTabsHandler
}

func (o *DeleteNoodleTabs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteNoodleTabsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
