// Code generated by go-swagger; DO NOT EDIT.

package noodle_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/mwinters-stuff/noodle/server/models"
)

// DeleteNoodleApplicationTabsHandlerFunc turns a function with the right signature into a delete noodle application tabs handler
type DeleteNoodleApplicationTabsHandlerFunc func(DeleteNoodleApplicationTabsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteNoodleApplicationTabsHandlerFunc) Handle(params DeleteNoodleApplicationTabsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteNoodleApplicationTabsHandler interface for that can handle valid delete noodle application tabs params
type DeleteNoodleApplicationTabsHandler interface {
	Handle(DeleteNoodleApplicationTabsParams, *models.Principal) middleware.Responder
}

// NewDeleteNoodleApplicationTabs creates a new http.Handler for the delete noodle application tabs operation
func NewDeleteNoodleApplicationTabs(ctx *middleware.Context, handler DeleteNoodleApplicationTabsHandler) *DeleteNoodleApplicationTabs {
	return &DeleteNoodleApplicationTabs{Context: ctx, Handler: handler}
}

/*
	DeleteNoodleApplicationTabs swagger:route DELETE /noodle/application-tabs noodle-api deleteNoodleApplicationTabs

Deletes the application_tab
*/
type DeleteNoodleApplicationTabs struct {
	Context *middleware.Context
	Handler DeleteNoodleApplicationTabsHandler
}

func (o *DeleteNoodleApplicationTabs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteNoodleApplicationTabsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
