// Code generated by go-swagger; DO NOT EDIT.

package noodle_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/mwinters-stuff/noodle/server/models"
)

// GetNoodleHeimdallReloadHandlerFunc turns a function with the right signature into a get noodle heimdall reload handler
type GetNoodleHeimdallReloadHandlerFunc func(GetNoodleHeimdallReloadParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetNoodleHeimdallReloadHandlerFunc) Handle(params GetNoodleHeimdallReloadParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetNoodleHeimdallReloadHandler interface for that can handle valid get noodle heimdall reload params
type GetNoodleHeimdallReloadHandler interface {
	Handle(GetNoodleHeimdallReloadParams, *models.Principal) middleware.Responder
}

// NewGetNoodleHeimdallReload creates a new http.Handler for the get noodle heimdall reload operation
func NewGetNoodleHeimdallReload(ctx *middleware.Context, handler GetNoodleHeimdallReloadHandler) *GetNoodleHeimdallReload {
	return &GetNoodleHeimdallReload{Context: ctx, Handler: handler}
}

/*
	GetNoodleHeimdallReload swagger:route GET /noodle/heimdall/reload noodle-api getNoodleHeimdallReload

Loads Hiemdall App Templates to Database
*/
type GetNoodleHeimdallReload struct {
	Context *middleware.Context
	Handler GetNoodleHeimdallReloadHandler
}

func (o *GetNoodleHeimdallReload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetNoodleHeimdallReloadParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
