// Code generated by go-swagger; DO NOT EDIT.

package noodle_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/mwinters-stuff/noodle/server/models"
)

// GetNoodleLdapReloadHandlerFunc turns a function with the right signature into a get noodle ldap reload handler
type GetNoodleLdapReloadHandlerFunc func(GetNoodleLdapReloadParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetNoodleLdapReloadHandlerFunc) Handle(params GetNoodleLdapReloadParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetNoodleLdapReloadHandler interface for that can handle valid get noodle ldap reload params
type GetNoodleLdapReloadHandler interface {
	Handle(GetNoodleLdapReloadParams, *models.Principal) middleware.Responder
}

// NewGetNoodleLdapReload creates a new http.Handler for the get noodle ldap reload operation
func NewGetNoodleLdapReload(ctx *middleware.Context, handler GetNoodleLdapReloadHandler) *GetNoodleLdapReload {
	return &GetNoodleLdapReload{Context: ctx, Handler: handler}
}

/*
	GetNoodleLdapReload swagger:route GET /noodle/ldap/reload noodle-api getNoodleLdapReload

Loads Users and Groups to Database
*/
type GetNoodleLdapReload struct {
	Context *middleware.Context
	Handler GetNoodleLdapReloadHandler
}

func (o *GetNoodleLdapReload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetNoodleLdapReloadParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
