// Code generated by go-swagger; DO NOT EDIT.

package noodle_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mwinters-stuff/noodle/server/models"
)

// GetNoodleTabsOKCode is the HTTP code returned for type GetNoodleTabsOK
const GetNoodleTabsOKCode int = 200

/*
GetNoodleTabsOK OK

swagger:response getNoodleTabsOK
*/
type GetNoodleTabsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Tab `json:"body,omitempty"`
}

// NewGetNoodleTabsOK creates GetNoodleTabsOK with default headers values
func NewGetNoodleTabsOK() *GetNoodleTabsOK {

	return &GetNoodleTabsOK{}
}

// WithPayload adds the payload to the get noodle tabs o k response
func (o *GetNoodleTabsOK) WithPayload(payload []*models.Tab) *GetNoodleTabsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get noodle tabs o k response
func (o *GetNoodleTabsOK) SetPayload(payload []*models.Tab) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNoodleTabsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Tab, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetNoodleTabsUnauthorizedCode is the HTTP code returned for type GetNoodleTabsUnauthorized
const GetNoodleTabsUnauthorizedCode int = 401

/*
GetNoodleTabsUnauthorized unauthorized

swagger:response getNoodleTabsUnauthorized
*/
type GetNoodleTabsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetNoodleTabsUnauthorized creates GetNoodleTabsUnauthorized with default headers values
func NewGetNoodleTabsUnauthorized() *GetNoodleTabsUnauthorized {

	return &GetNoodleTabsUnauthorized{}
}

// WithPayload adds the payload to the get noodle tabs unauthorized response
func (o *GetNoodleTabsUnauthorized) WithPayload(payload *models.Error) *GetNoodleTabsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get noodle tabs unauthorized response
func (o *GetNoodleTabsUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNoodleTabsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetNoodleTabsConflictCode is the HTTP code returned for type GetNoodleTabsConflict
const GetNoodleTabsConflictCode int = 409

/*
GetNoodleTabsConflict Failed

swagger:response getNoodleTabsConflict
*/
type GetNoodleTabsConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetNoodleTabsConflict creates GetNoodleTabsConflict with default headers values
func NewGetNoodleTabsConflict() *GetNoodleTabsConflict {

	return &GetNoodleTabsConflict{}
}

// WithPayload adds the payload to the get noodle tabs conflict response
func (o *GetNoodleTabsConflict) WithPayload(payload *models.Error) *GetNoodleTabsConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get noodle tabs conflict response
func (o *GetNoodleTabsConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNoodleTabsConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
