// Code generated by go-swagger; DO NOT EDIT.

package noodle_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetNoodleUsersHandlerFunc turns a function with the right signature into a get noodle users handler
type GetNoodleUsersHandlerFunc func(GetNoodleUsersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetNoodleUsersHandlerFunc) Handle(params GetNoodleUsersParams) middleware.Responder {
	return fn(params)
}

// GetNoodleUsersHandler interface for that can handle valid get noodle users params
type GetNoodleUsersHandler interface {
	Handle(GetNoodleUsersParams) middleware.Responder
}

// NewGetNoodleUsers creates a new http.Handler for the get noodle users operation
func NewGetNoodleUsers(ctx *middleware.Context, handler GetNoodleUsersHandler) *GetNoodleUsers {
	return &GetNoodleUsers{Context: ctx, Handler: handler}
}

/*
	GetNoodleUsers swagger:route GET /noodle/users noodle-api getNoodleUsers

Gets the list of users
*/
type GetNoodleUsers struct {
	Context *middleware.Context
	Handler GetNoodleUsersHandler
}

func (o *GetNoodleUsers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetNoodleUsersParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
