// Code generated by go-swagger; DO NOT EDIT.

package noodle_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/mwinters-stuff/noodle/server/models"
)

// GetNoodleApplicationTabsHandlerFunc turns a function with the right signature into a get noodle application tabs handler
type GetNoodleApplicationTabsHandlerFunc func(GetNoodleApplicationTabsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetNoodleApplicationTabsHandlerFunc) Handle(params GetNoodleApplicationTabsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetNoodleApplicationTabsHandler interface for that can handle valid get noodle application tabs params
type GetNoodleApplicationTabsHandler interface {
	Handle(GetNoodleApplicationTabsParams, *models.Principal) middleware.Responder
}

// NewGetNoodleApplicationTabs creates a new http.Handler for the get noodle application tabs operation
func NewGetNoodleApplicationTabs(ctx *middleware.Context, handler GetNoodleApplicationTabsHandler) *GetNoodleApplicationTabs {
	return &GetNoodleApplicationTabs{Context: ctx, Handler: handler}
}

/*
	GetNoodleApplicationTabs swagger:route GET /noodle/application-tabs noodle-api getNoodleApplicationTabs

Gets the list of applications under the tab
*/
type GetNoodleApplicationTabs struct {
	Context *middleware.Context
	Handler GetNoodleApplicationTabsHandler
}

func (o *GetNoodleApplicationTabs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetNoodleApplicationTabsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
