// Code generated by go-swagger; DO NOT EDIT.

package noodle_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/mwinters-stuff/noodle/server/models"
)

// GetNoodleGroupApplicationsHandlerFunc turns a function with the right signature into a get noodle group applications handler
type GetNoodleGroupApplicationsHandlerFunc func(GetNoodleGroupApplicationsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetNoodleGroupApplicationsHandlerFunc) Handle(params GetNoodleGroupApplicationsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetNoodleGroupApplicationsHandler interface for that can handle valid get noodle group applications params
type GetNoodleGroupApplicationsHandler interface {
	Handle(GetNoodleGroupApplicationsParams, *models.Principal) middleware.Responder
}

// NewGetNoodleGroupApplications creates a new http.Handler for the get noodle group applications operation
func NewGetNoodleGroupApplications(ctx *middleware.Context, handler GetNoodleGroupApplicationsHandler) *GetNoodleGroupApplications {
	return &GetNoodleGroupApplications{Context: ctx, Handler: handler}
}

/*
	GetNoodleGroupApplications swagger:route GET /noodle/group-applications noodle-api getNoodleGroupApplications

Gets the list of group applications
*/
type GetNoodleGroupApplications struct {
	Context *middleware.Context
	Handler GetNoodleGroupApplicationsHandler
}

func (o *GetNoodleGroupApplications) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetNoodleGroupApplicationsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
