// Code generated by go-swagger; DO NOT EDIT.

package noodle_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mwinters-stuff/noodle/server/models"
)

// PostNoodleUploadIconOKCode is the HTTP code returned for type PostNoodleUploadIconOK
const PostNoodleUploadIconOKCode int = 200

/*
PostNoodleUploadIconOK OK

swagger:response postNoodleUploadIconOK
*/
type PostNoodleUploadIconOK struct {
}

// NewPostNoodleUploadIconOK creates PostNoodleUploadIconOK with default headers values
func NewPostNoodleUploadIconOK() *PostNoodleUploadIconOK {

	return &PostNoodleUploadIconOK{}
}

// WriteResponse to the client
func (o *PostNoodleUploadIconOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostNoodleUploadIconUnauthorizedCode is the HTTP code returned for type PostNoodleUploadIconUnauthorized
const PostNoodleUploadIconUnauthorizedCode int = 401

/*
PostNoodleUploadIconUnauthorized unauthorized

swagger:response postNoodleUploadIconUnauthorized
*/
type PostNoodleUploadIconUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostNoodleUploadIconUnauthorized creates PostNoodleUploadIconUnauthorized with default headers values
func NewPostNoodleUploadIconUnauthorized() *PostNoodleUploadIconUnauthorized {

	return &PostNoodleUploadIconUnauthorized{}
}

// WithPayload adds the payload to the post noodle upload icon unauthorized response
func (o *PostNoodleUploadIconUnauthorized) WithPayload(payload *models.Error) *PostNoodleUploadIconUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post noodle upload icon unauthorized response
func (o *PostNoodleUploadIconUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostNoodleUploadIconUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostNoodleUploadIconConflictCode is the HTTP code returned for type PostNoodleUploadIconConflict
const PostNoodleUploadIconConflictCode int = 409

/*
PostNoodleUploadIconConflict Failed

swagger:response postNoodleUploadIconConflict
*/
type PostNoodleUploadIconConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostNoodleUploadIconConflict creates PostNoodleUploadIconConflict with default headers values
func NewPostNoodleUploadIconConflict() *PostNoodleUploadIconConflict {

	return &PostNoodleUploadIconConflict{}
}

// WithPayload adds the payload to the post noodle upload icon conflict response
func (o *PostNoodleUploadIconConflict) WithPayload(payload *models.Error) *PostNoodleUploadIconConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post noodle upload icon conflict response
func (o *PostNoodleUploadIconConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostNoodleUploadIconConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
