// Code generated by go-swagger; DO NOT EDIT.

package noodle_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/mwinters-stuff/noodle/server/models"
)

// PostNoodleApplicationTabsHandlerFunc turns a function with the right signature into a post noodle application tabs handler
type PostNoodleApplicationTabsHandlerFunc func(PostNoodleApplicationTabsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PostNoodleApplicationTabsHandlerFunc) Handle(params PostNoodleApplicationTabsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PostNoodleApplicationTabsHandler interface for that can handle valid post noodle application tabs params
type PostNoodleApplicationTabsHandler interface {
	Handle(PostNoodleApplicationTabsParams, *models.Principal) middleware.Responder
}

// NewPostNoodleApplicationTabs creates a new http.Handler for the post noodle application tabs operation
func NewPostNoodleApplicationTabs(ctx *middleware.Context, handler PostNoodleApplicationTabsHandler) *PostNoodleApplicationTabs {
	return &PostNoodleApplicationTabs{Context: ctx, Handler: handler}
}

/*
	PostNoodleApplicationTabs swagger:route POST /noodle/application-tabs noodle-api postNoodleApplicationTabs

Adds a new application in a tab, changes tab, or display order
*/
type PostNoodleApplicationTabs struct {
	Context *middleware.Context
	Handler PostNoodleApplicationTabsHandler
}

func (o *PostNoodleApplicationTabs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostNoodleApplicationTabsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
