// Code generated by go-swagger; DO NOT EDIT.

package noodle_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mwinters-stuff/noodle/server/models"
)

// PostNoodleUsersOKCode is the HTTP code returned for type PostNoodleUsersOK
const PostNoodleUsersOKCode int = 200

/*
PostNoodleUsersOK OK

swagger:response postNoodleUsersOK
*/
type PostNoodleUsersOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewPostNoodleUsersOK creates PostNoodleUsersOK with default headers values
func NewPostNoodleUsersOK() *PostNoodleUsersOK {

	return &PostNoodleUsersOK{}
}

// WithPayload adds the payload to the post noodle users o k response
func (o *PostNoodleUsersOK) WithPayload(payload *models.User) *PostNoodleUsersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post noodle users o k response
func (o *PostNoodleUsersOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostNoodleUsersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostNoodleUsersConflictCode is the HTTP code returned for type PostNoodleUsersConflict
const PostNoodleUsersConflictCode int = 409

/*
PostNoodleUsersConflict Failed

swagger:response postNoodleUsersConflict
*/
type PostNoodleUsersConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostNoodleUsersConflict creates PostNoodleUsersConflict with default headers values
func NewPostNoodleUsersConflict() *PostNoodleUsersConflict {

	return &PostNoodleUsersConflict{}
}

// WithPayload adds the payload to the post noodle users conflict response
func (o *PostNoodleUsersConflict) WithPayload(payload *models.Error) *PostNoodleUsersConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post noodle users conflict response
func (o *PostNoodleUsersConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostNoodleUsersConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
