// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	pgconn "github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// AfterConnectFunc is an autogenerated mock type for the AfterConnectFunc type
type AfterConnectFunc struct {
	mock.Mock
}

type AfterConnectFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *AfterConnectFunc) EXPECT() *AfterConnectFunc_Expecter {
	return &AfterConnectFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, _a1
func (_m *AfterConnectFunc) Execute(ctx context.Context, _a1 *pgconn.PgConn) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *pgconn.PgConn) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AfterConnectFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type AfterConnectFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *pgconn.PgConn
func (_e *AfterConnectFunc_Expecter) Execute(ctx interface{}, _a1 interface{}) *AfterConnectFunc_Execute_Call {
	return &AfterConnectFunc_Execute_Call{Call: _e.mock.On("Execute", ctx, _a1)}
}

func (_c *AfterConnectFunc_Execute_Call) Run(run func(ctx context.Context, _a1 *pgconn.PgConn)) *AfterConnectFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*pgconn.PgConn))
	})
	return _c
}

func (_c *AfterConnectFunc_Execute_Call) Return(_a0 error) *AfterConnectFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewAfterConnectFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewAfterConnectFunc creates a new instance of AfterConnectFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAfterConnectFunc(t mockConstructorTestingTNewAfterConnectFunc) *AfterConnectFunc {
	mock := &AfterConnectFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
