// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
)

// BitsValuer is an autogenerated mock type for the BitsValuer type
type BitsValuer struct {
	mock.Mock
}

type BitsValuer_Expecter struct {
	mock *mock.Mock
}

func (_m *BitsValuer) EXPECT() *BitsValuer_Expecter {
	return &BitsValuer_Expecter{mock: &_m.Mock}
}

// BitsValue provides a mock function with given fields:
func (_m *BitsValuer) BitsValue() (pgtype.Bits, error) {
	ret := _m.Called()

	var r0 pgtype.Bits
	if rf, ok := ret.Get(0).(func() pgtype.Bits); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(pgtype.Bits)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BitsValuer_BitsValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BitsValue'
type BitsValuer_BitsValue_Call struct {
	*mock.Call
}

// BitsValue is a helper method to define mock.On call
func (_e *BitsValuer_Expecter) BitsValue() *BitsValuer_BitsValue_Call {
	return &BitsValuer_BitsValue_Call{Call: _e.mock.On("BitsValue")}
}

func (_c *BitsValuer_BitsValue_Call) Run(run func()) *BitsValuer_BitsValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BitsValuer_BitsValue_Call) Return(_a0 pgtype.Bits, _a1 error) *BitsValuer_BitsValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewBitsValuer interface {
	mock.TestingT
	Cleanup(func())
}

// NewBitsValuer creates a new instance of BitsValuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBitsValuer(t mockConstructorTestingTNewBitsValuer) *BitsValuer {
	mock := &BitsValuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
