// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
)

// BoolValuer is an autogenerated mock type for the BoolValuer type
type BoolValuer struct {
	mock.Mock
}

type BoolValuer_Expecter struct {
	mock *mock.Mock
}

func (_m *BoolValuer) EXPECT() *BoolValuer_Expecter {
	return &BoolValuer_Expecter{mock: &_m.Mock}
}

// BoolValue provides a mock function with given fields:
func (_m *BoolValuer) BoolValue() (pgtype.Bool, error) {
	ret := _m.Called()

	var r0 pgtype.Bool
	if rf, ok := ret.Get(0).(func() pgtype.Bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(pgtype.Bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BoolValuer_BoolValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BoolValue'
type BoolValuer_BoolValue_Call struct {
	*mock.Call
}

// BoolValue is a helper method to define mock.On call
func (_e *BoolValuer_Expecter) BoolValue() *BoolValuer_BoolValue_Call {
	return &BoolValuer_BoolValue_Call{Call: _e.mock.On("BoolValue")}
}

func (_c *BoolValuer_BoolValue_Call) Run(run func()) *BoolValuer_BoolValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BoolValuer_BoolValue_Call) Return(_a0 pgtype.Bool, _a1 error) *BoolValuer_BoolValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewBoolValuer interface {
	mock.TestingT
	Cleanup(func())
}

// NewBoolValuer creates a new instance of BoolValuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBoolValuer(t mockConstructorTestingTNewBoolValuer) *BoolValuer {
	mock := &BoolValuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
