// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// CopyFromTracer is an autogenerated mock type for the CopyFromTracer type
type CopyFromTracer struct {
	mock.Mock
}

type CopyFromTracer_Expecter struct {
	mock *mock.Mock
}

func (_m *CopyFromTracer) EXPECT() *CopyFromTracer_Expecter {
	return &CopyFromTracer_Expecter{mock: &_m.Mock}
}

// TraceCopyFromEnd provides a mock function with given fields: ctx, conn, data
func (_m *CopyFromTracer) TraceCopyFromEnd(ctx context.Context, conn *pgx.Conn, data pgx.TraceCopyFromEndData) {
	_m.Called(ctx, conn, data)
}

// CopyFromTracer_TraceCopyFromEnd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TraceCopyFromEnd'
type CopyFromTracer_TraceCopyFromEnd_Call struct {
	*mock.Call
}

// TraceCopyFromEnd is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *pgx.Conn
//   - data pgx.TraceCopyFromEndData
func (_e *CopyFromTracer_Expecter) TraceCopyFromEnd(ctx interface{}, conn interface{}, data interface{}) *CopyFromTracer_TraceCopyFromEnd_Call {
	return &CopyFromTracer_TraceCopyFromEnd_Call{Call: _e.mock.On("TraceCopyFromEnd", ctx, conn, data)}
}

func (_c *CopyFromTracer_TraceCopyFromEnd_Call) Run(run func(ctx context.Context, conn *pgx.Conn, data pgx.TraceCopyFromEndData)) *CopyFromTracer_TraceCopyFromEnd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*pgx.Conn), args[2].(pgx.TraceCopyFromEndData))
	})
	return _c
}

func (_c *CopyFromTracer_TraceCopyFromEnd_Call) Return() *CopyFromTracer_TraceCopyFromEnd_Call {
	_c.Call.Return()
	return _c
}

// TraceCopyFromStart provides a mock function with given fields: ctx, conn, data
func (_m *CopyFromTracer) TraceCopyFromStart(ctx context.Context, conn *pgx.Conn, data pgx.TraceCopyFromStartData) context.Context {
	ret := _m.Called(ctx, conn, data)

	var r0 context.Context
	if rf, ok := ret.Get(0).(func(context.Context, *pgx.Conn, pgx.TraceCopyFromStartData) context.Context); ok {
		r0 = rf(ctx, conn, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// CopyFromTracer_TraceCopyFromStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TraceCopyFromStart'
type CopyFromTracer_TraceCopyFromStart_Call struct {
	*mock.Call
}

// TraceCopyFromStart is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *pgx.Conn
//   - data pgx.TraceCopyFromStartData
func (_e *CopyFromTracer_Expecter) TraceCopyFromStart(ctx interface{}, conn interface{}, data interface{}) *CopyFromTracer_TraceCopyFromStart_Call {
	return &CopyFromTracer_TraceCopyFromStart_Call{Call: _e.mock.On("TraceCopyFromStart", ctx, conn, data)}
}

func (_c *CopyFromTracer_TraceCopyFromStart_Call) Run(run func(ctx context.Context, conn *pgx.Conn, data pgx.TraceCopyFromStartData)) *CopyFromTracer_TraceCopyFromStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*pgx.Conn), args[2].(pgx.TraceCopyFromStartData))
	})
	return _c
}

func (_c *CopyFromTracer_TraceCopyFromStart_Call) Return(_a0 context.Context) *CopyFromTracer_TraceCopyFromStart_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewCopyFromTracer interface {
	mock.TestingT
	Cleanup(func())
}

// NewCopyFromTracer creates a new instance of CopyFromTracer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCopyFromTracer(t mockConstructorTestingTNewCopyFromTracer) *CopyFromTracer {
	mock := &CopyFromTracer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
