// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
)

// DateValuer is an autogenerated mock type for the DateValuer type
type DateValuer struct {
	mock.Mock
}

type DateValuer_Expecter struct {
	mock *mock.Mock
}

func (_m *DateValuer) EXPECT() *DateValuer_Expecter {
	return &DateValuer_Expecter{mock: &_m.Mock}
}

// DateValue provides a mock function with given fields:
func (_m *DateValuer) DateValue() (pgtype.Date, error) {
	ret := _m.Called()

	var r0 pgtype.Date
	if rf, ok := ret.Get(0).(func() pgtype.Date); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(pgtype.Date)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DateValuer_DateValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DateValue'
type DateValuer_DateValue_Call struct {
	*mock.Call
}

// DateValue is a helper method to define mock.On call
func (_e *DateValuer_Expecter) DateValue() *DateValuer_DateValue_Call {
	return &DateValuer_DateValue_Call{Call: _e.mock.On("DateValue")}
}

func (_c *DateValuer_DateValue_Call) Run(run func()) *DateValuer_DateValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DateValuer_DateValue_Call) Return(_a0 pgtype.Date, _a1 error) *DateValuer_DateValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewDateValuer interface {
	mock.TestingT
	Cleanup(func())
}

// NewDateValuer creates a new instance of DateValuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDateValuer(t mockConstructorTestingTNewDateValuer) *DateValuer {
	mock := &DateValuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
