// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
)

// HstoreValuer is an autogenerated mock type for the HstoreValuer type
type HstoreValuer struct {
	mock.Mock
}

type HstoreValuer_Expecter struct {
	mock *mock.Mock
}

func (_m *HstoreValuer) EXPECT() *HstoreValuer_Expecter {
	return &HstoreValuer_Expecter{mock: &_m.Mock}
}

// HstoreValue provides a mock function with given fields:
func (_m *HstoreValuer) HstoreValue() (pgtype.Hstore, error) {
	ret := _m.Called()

	var r0 pgtype.Hstore
	if rf, ok := ret.Get(0).(func() pgtype.Hstore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgtype.Hstore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HstoreValuer_HstoreValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HstoreValue'
type HstoreValuer_HstoreValue_Call struct {
	*mock.Call
}

// HstoreValue is a helper method to define mock.On call
func (_e *HstoreValuer_Expecter) HstoreValue() *HstoreValuer_HstoreValue_Call {
	return &HstoreValuer_HstoreValue_Call{Call: _e.mock.On("HstoreValue")}
}

func (_c *HstoreValuer_HstoreValue_Call) Run(run func()) *HstoreValuer_HstoreValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HstoreValuer_HstoreValue_Call) Return(_a0 pgtype.Hstore, _a1 error) *HstoreValuer_HstoreValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewHstoreValuer interface {
	mock.TestingT
	Cleanup(func())
}

// NewHstoreValuer creates a new instance of HstoreValuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHstoreValuer(t mockConstructorTestingTNewHstoreValuer) *HstoreValuer {
	mock := &HstoreValuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
