// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
)

// Int64Valuer is an autogenerated mock type for the Int64Valuer type
type Int64Valuer struct {
	mock.Mock
}

type Int64Valuer_Expecter struct {
	mock *mock.Mock
}

func (_m *Int64Valuer) EXPECT() *Int64Valuer_Expecter {
	return &Int64Valuer_Expecter{mock: &_m.Mock}
}

// Int64Value provides a mock function with given fields:
func (_m *Int64Valuer) Int64Value() (pgtype.Int8, error) {
	ret := _m.Called()

	var r0 pgtype.Int8
	if rf, ok := ret.Get(0).(func() pgtype.Int8); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(pgtype.Int8)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Int64Valuer_Int64Value_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Int64Value'
type Int64Valuer_Int64Value_Call struct {
	*mock.Call
}

// Int64Value is a helper method to define mock.On call
func (_e *Int64Valuer_Expecter) Int64Value() *Int64Valuer_Int64Value_Call {
	return &Int64Valuer_Int64Value_Call{Call: _e.mock.On("Int64Value")}
}

func (_c *Int64Valuer_Int64Value_Call) Run(run func()) *Int64Valuer_Int64Value_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Int64Valuer_Int64Value_Call) Return(_a0 pgtype.Int8, _a1 error) *Int64Valuer_Int64Value_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewInt64Valuer interface {
	mock.TestingT
	Cleanup(func())
}

// NewInt64Valuer creates a new instance of Int64Valuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInt64Valuer(t mockConstructorTestingTNewInt64Valuer) *Int64Valuer {
	mock := &Int64Valuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
