// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
)

// IntervalScanner is an autogenerated mock type for the IntervalScanner type
type IntervalScanner struct {
	mock.Mock
}

type IntervalScanner_Expecter struct {
	mock *mock.Mock
}

func (_m *IntervalScanner) EXPECT() *IntervalScanner_Expecter {
	return &IntervalScanner_Expecter{mock: &_m.Mock}
}

// ScanInterval provides a mock function with given fields: v
func (_m *IntervalScanner) ScanInterval(v pgtype.Interval) error {
	ret := _m.Called(v)

	var r0 error
	if rf, ok := ret.Get(0).(func(pgtype.Interval) error); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IntervalScanner_ScanInterval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanInterval'
type IntervalScanner_ScanInterval_Call struct {
	*mock.Call
}

// ScanInterval is a helper method to define mock.On call
//   - v pgtype.Interval
func (_e *IntervalScanner_Expecter) ScanInterval(v interface{}) *IntervalScanner_ScanInterval_Call {
	return &IntervalScanner_ScanInterval_Call{Call: _e.mock.On("ScanInterval", v)}
}

func (_c *IntervalScanner_ScanInterval_Call) Run(run func(v pgtype.Interval)) *IntervalScanner_ScanInterval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pgtype.Interval))
	})
	return _c
}

func (_c *IntervalScanner_ScanInterval_Call) Return(_a0 error) *IntervalScanner_ScanInterval_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewIntervalScanner interface {
	mock.TestingT
	Cleanup(func())
}

// NewIntervalScanner creates a new instance of IntervalScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIntervalScanner(t mockConstructorTestingTNewIntervalScanner) *IntervalScanner {
	mock := &IntervalScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
