// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
)

// IntervalValuer is an autogenerated mock type for the IntervalValuer type
type IntervalValuer struct {
	mock.Mock
}

type IntervalValuer_Expecter struct {
	mock *mock.Mock
}

func (_m *IntervalValuer) EXPECT() *IntervalValuer_Expecter {
	return &IntervalValuer_Expecter{mock: &_m.Mock}
}

// IntervalValue provides a mock function with given fields:
func (_m *IntervalValuer) IntervalValue() (pgtype.Interval, error) {
	ret := _m.Called()

	var r0 pgtype.Interval
	if rf, ok := ret.Get(0).(func() pgtype.Interval); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(pgtype.Interval)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IntervalValuer_IntervalValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IntervalValue'
type IntervalValuer_IntervalValue_Call struct {
	*mock.Call
}

// IntervalValue is a helper method to define mock.On call
func (_e *IntervalValuer_Expecter) IntervalValue() *IntervalValuer_IntervalValue_Call {
	return &IntervalValuer_IntervalValue_Call{Call: _e.mock.On("IntervalValue")}
}

func (_c *IntervalValuer_IntervalValue_Call) Run(run func()) *IntervalValuer_IntervalValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IntervalValuer_IntervalValue_Call) Return(_a0 pgtype.Interval, _a1 error) *IntervalValuer_IntervalValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewIntervalValuer interface {
	mock.TestingT
	Cleanup(func())
}

// NewIntervalValuer creates a new instance of IntervalValuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIntervalValuer(t mockConstructorTestingTNewIntervalValuer) *IntervalValuer {
	mock := &IntervalValuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
