// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
)

// LsegScanner is an autogenerated mock type for the LsegScanner type
type LsegScanner struct {
	mock.Mock
}

type LsegScanner_Expecter struct {
	mock *mock.Mock
}

func (_m *LsegScanner) EXPECT() *LsegScanner_Expecter {
	return &LsegScanner_Expecter{mock: &_m.Mock}
}

// ScanLseg provides a mock function with given fields: v
func (_m *LsegScanner) ScanLseg(v pgtype.Lseg) error {
	ret := _m.Called(v)

	var r0 error
	if rf, ok := ret.Get(0).(func(pgtype.Lseg) error); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LsegScanner_ScanLseg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanLseg'
type LsegScanner_ScanLseg_Call struct {
	*mock.Call
}

// ScanLseg is a helper method to define mock.On call
//   - v pgtype.Lseg
func (_e *LsegScanner_Expecter) ScanLseg(v interface{}) *LsegScanner_ScanLseg_Call {
	return &LsegScanner_ScanLseg_Call{Call: _e.mock.On("ScanLseg", v)}
}

func (_c *LsegScanner_ScanLseg_Call) Run(run func(v pgtype.Lseg)) *LsegScanner_ScanLseg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pgtype.Lseg))
	})
	return _c
}

func (_c *LsegScanner_ScanLseg_Call) Return(_a0 error) *LsegScanner_ScanLseg_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewLsegScanner interface {
	mock.TestingT
	Cleanup(func())
}

// NewLsegScanner creates a new instance of LsegScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLsegScanner(t mockConstructorTestingTNewLsegScanner) *LsegScanner {
	mock := &LsegScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
