// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Message is an autogenerated mock type for the Message type
type Message struct {
	mock.Mock
}

type Message_Expecter struct {
	mock *mock.Mock
}

func (_m *Message) EXPECT() *Message_Expecter {
	return &Message_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function with given fields: data
func (_m *Message) Decode(data []byte) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Message_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type Message_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - data []byte
func (_e *Message_Expecter) Decode(data interface{}) *Message_Decode_Call {
	return &Message_Decode_Call{Call: _e.mock.On("Decode", data)}
}

func (_c *Message_Decode_Call) Run(run func(data []byte)) *Message_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *Message_Decode_Call) Return(_a0 error) *Message_Decode_Call {
	_c.Call.Return(_a0)
	return _c
}

// Encode provides a mock function with given fields: dst
func (_m *Message) Encode(dst []byte) []byte {
	ret := _m.Called(dst)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(dst)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// Message_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type Message_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - dst []byte
func (_e *Message_Expecter) Encode(dst interface{}) *Message_Encode_Call {
	return &Message_Encode_Call{Call: _e.mock.On("Encode", dst)}
}

func (_c *Message_Encode_Call) Run(run func(dst []byte)) *Message_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *Message_Encode_Call) Return(_a0 []byte) *Message_Encode_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewMessage interface {
	mock.TestingT
	Cleanup(func())
}

// NewMessage creates a new instance of Message. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMessage(t mockConstructorTestingTNewMessage) *Message {
	mock := &Message{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
