// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
)

// NumericValuer is an autogenerated mock type for the NumericValuer type
type NumericValuer struct {
	mock.Mock
}

type NumericValuer_Expecter struct {
	mock *mock.Mock
}

func (_m *NumericValuer) EXPECT() *NumericValuer_Expecter {
	return &NumericValuer_Expecter{mock: &_m.Mock}
}

// NumericValue provides a mock function with given fields:
func (_m *NumericValuer) NumericValue() (pgtype.Numeric, error) {
	ret := _m.Called()

	var r0 pgtype.Numeric
	if rf, ok := ret.Get(0).(func() pgtype.Numeric); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(pgtype.Numeric)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NumericValuer_NumericValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NumericValue'
type NumericValuer_NumericValue_Call struct {
	*mock.Call
}

// NumericValue is a helper method to define mock.On call
func (_e *NumericValuer_Expecter) NumericValue() *NumericValuer_NumericValue_Call {
	return &NumericValuer_NumericValue_Call{Call: _e.mock.On("NumericValue")}
}

func (_c *NumericValuer_NumericValue_Call) Run(run func()) *NumericValuer_NumericValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NumericValuer_NumericValue_Call) Return(_a0 pgtype.Numeric, _a1 error) *NumericValuer_NumericValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewNumericValuer interface {
	mock.TestingT
	Cleanup(func())
}

// NewNumericValuer creates a new instance of NumericValuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNumericValuer(t mockConstructorTestingTNewNumericValuer) *NumericValuer {
	mock := &NumericValuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
