// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// PrepareTracer is an autogenerated mock type for the PrepareTracer type
type PrepareTracer struct {
	mock.Mock
}

type PrepareTracer_Expecter struct {
	mock *mock.Mock
}

func (_m *PrepareTracer) EXPECT() *PrepareTracer_Expecter {
	return &PrepareTracer_Expecter{mock: &_m.Mock}
}

// TracePrepareEnd provides a mock function with given fields: ctx, conn, data
func (_m *PrepareTracer) TracePrepareEnd(ctx context.Context, conn *pgx.Conn, data pgx.TracePrepareEndData) {
	_m.Called(ctx, conn, data)
}

// PrepareTracer_TracePrepareEnd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TracePrepareEnd'
type PrepareTracer_TracePrepareEnd_Call struct {
	*mock.Call
}

// TracePrepareEnd is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *pgx.Conn
//   - data pgx.TracePrepareEndData
func (_e *PrepareTracer_Expecter) TracePrepareEnd(ctx interface{}, conn interface{}, data interface{}) *PrepareTracer_TracePrepareEnd_Call {
	return &PrepareTracer_TracePrepareEnd_Call{Call: _e.mock.On("TracePrepareEnd", ctx, conn, data)}
}

func (_c *PrepareTracer_TracePrepareEnd_Call) Run(run func(ctx context.Context, conn *pgx.Conn, data pgx.TracePrepareEndData)) *PrepareTracer_TracePrepareEnd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*pgx.Conn), args[2].(pgx.TracePrepareEndData))
	})
	return _c
}

func (_c *PrepareTracer_TracePrepareEnd_Call) Return() *PrepareTracer_TracePrepareEnd_Call {
	_c.Call.Return()
	return _c
}

// TracePrepareStart provides a mock function with given fields: ctx, conn, data
func (_m *PrepareTracer) TracePrepareStart(ctx context.Context, conn *pgx.Conn, data pgx.TracePrepareStartData) context.Context {
	ret := _m.Called(ctx, conn, data)

	var r0 context.Context
	if rf, ok := ret.Get(0).(func(context.Context, *pgx.Conn, pgx.TracePrepareStartData) context.Context); ok {
		r0 = rf(ctx, conn, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// PrepareTracer_TracePrepareStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TracePrepareStart'
type PrepareTracer_TracePrepareStart_Call struct {
	*mock.Call
}

// TracePrepareStart is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *pgx.Conn
//   - data pgx.TracePrepareStartData
func (_e *PrepareTracer_Expecter) TracePrepareStart(ctx interface{}, conn interface{}, data interface{}) *PrepareTracer_TracePrepareStart_Call {
	return &PrepareTracer_TracePrepareStart_Call{Call: _e.mock.On("TracePrepareStart", ctx, conn, data)}
}

func (_c *PrepareTracer_TracePrepareStart_Call) Run(run func(ctx context.Context, conn *pgx.Conn, data pgx.TracePrepareStartData)) *PrepareTracer_TracePrepareStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*pgx.Conn), args[2].(pgx.TracePrepareStartData))
	})
	return _c
}

func (_c *PrepareTracer_TracePrepareStart_Call) Return(_a0 context.Context) *PrepareTracer_TracePrepareStart_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewPrepareTracer interface {
	mock.TestingT
	Cleanup(func())
}

// NewPrepareTracer creates a new instance of PrepareTracer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPrepareTracer(t mockConstructorTestingTNewPrepareTracer) *PrepareTracer {
	mock := &PrepareTracer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
