// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	pgconn "github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// Rows is an autogenerated mock type for the Rows type
type Rows struct {
	mock.Mock
}

type Rows_Expecter struct {
	mock *mock.Mock
}

func (_m *Rows) EXPECT() *Rows_Expecter {
	return &Rows_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *Rows) Close() {
	_m.Called()
}

// Rows_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Rows_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Rows_Expecter) Close() *Rows_Close_Call {
	return &Rows_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Rows_Close_Call) Run(run func()) *Rows_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Rows_Close_Call) Return() *Rows_Close_Call {
	_c.Call.Return()
	return _c
}

// CommandTag provides a mock function with given fields:
func (_m *Rows) CommandTag() pgconn.CommandTag {
	ret := _m.Called()

	var r0 pgconn.CommandTag
	if rf, ok := ret.Get(0).(func() pgconn.CommandTag); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}

	return r0
}

// Rows_CommandTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommandTag'
type Rows_CommandTag_Call struct {
	*mock.Call
}

// CommandTag is a helper method to define mock.On call
func (_e *Rows_Expecter) CommandTag() *Rows_CommandTag_Call {
	return &Rows_CommandTag_Call{Call: _e.mock.On("CommandTag")}
}

func (_c *Rows_CommandTag_Call) Run(run func()) *Rows_CommandTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Rows_CommandTag_Call) Return(_a0 pgconn.CommandTag) *Rows_CommandTag_Call {
	_c.Call.Return(_a0)
	return _c
}

// Conn provides a mock function with given fields:
func (_m *Rows) Conn() *pgx.Conn {
	ret := _m.Called()

	var r0 *pgx.Conn
	if rf, ok := ret.Get(0).(func() *pgx.Conn); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgx.Conn)
		}
	}

	return r0
}

// Rows_Conn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Conn'
type Rows_Conn_Call struct {
	*mock.Call
}

// Conn is a helper method to define mock.On call
func (_e *Rows_Expecter) Conn() *Rows_Conn_Call {
	return &Rows_Conn_Call{Call: _e.mock.On("Conn")}
}

func (_c *Rows_Conn_Call) Run(run func()) *Rows_Conn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Rows_Conn_Call) Return(_a0 *pgx.Conn) *Rows_Conn_Call {
	_c.Call.Return(_a0)
	return _c
}

// Err provides a mock function with given fields:
func (_m *Rows) Err() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Rows_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type Rows_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *Rows_Expecter) Err() *Rows_Err_Call {
	return &Rows_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *Rows_Err_Call) Run(run func()) *Rows_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Rows_Err_Call) Return(_a0 error) *Rows_Err_Call {
	_c.Call.Return(_a0)
	return _c
}

// FieldDescriptions provides a mock function with given fields:
func (_m *Rows) FieldDescriptions() []pgconn.FieldDescription {
	ret := _m.Called()

	var r0 []pgconn.FieldDescription
	if rf, ok := ret.Get(0).(func() []pgconn.FieldDescription); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pgconn.FieldDescription)
		}
	}

	return r0
}

// Rows_FieldDescriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FieldDescriptions'
type Rows_FieldDescriptions_Call struct {
	*mock.Call
}

// FieldDescriptions is a helper method to define mock.On call
func (_e *Rows_Expecter) FieldDescriptions() *Rows_FieldDescriptions_Call {
	return &Rows_FieldDescriptions_Call{Call: _e.mock.On("FieldDescriptions")}
}

func (_c *Rows_FieldDescriptions_Call) Run(run func()) *Rows_FieldDescriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Rows_FieldDescriptions_Call) Return(_a0 []pgconn.FieldDescription) *Rows_FieldDescriptions_Call {
	_c.Call.Return(_a0)
	return _c
}

// Next provides a mock function with given fields:
func (_m *Rows) Next() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Rows_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type Rows_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *Rows_Expecter) Next() *Rows_Next_Call {
	return &Rows_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *Rows_Next_Call) Run(run func()) *Rows_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Rows_Next_Call) Return(_a0 bool) *Rows_Next_Call {
	_c.Call.Return(_a0)
	return _c
}

// RawValues provides a mock function with given fields:
func (_m *Rows) RawValues() [][]byte {
	ret := _m.Called()

	var r0 [][]byte
	if rf, ok := ret.Get(0).(func() [][]byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}

	return r0
}

// Rows_RawValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RawValues'
type Rows_RawValues_Call struct {
	*mock.Call
}

// RawValues is a helper method to define mock.On call
func (_e *Rows_Expecter) RawValues() *Rows_RawValues_Call {
	return &Rows_RawValues_Call{Call: _e.mock.On("RawValues")}
}

func (_c *Rows_RawValues_Call) Run(run func()) *Rows_RawValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Rows_RawValues_Call) Return(_a0 [][]byte) *Rows_RawValues_Call {
	_c.Call.Return(_a0)
	return _c
}

// Scan provides a mock function with given fields: dest
func (_m *Rows) Scan(dest ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, dest...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...interface{}) error); ok {
		r0 = rf(dest...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Rows_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type Rows_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - dest ...interface{}
func (_e *Rows_Expecter) Scan(dest ...interface{}) *Rows_Scan_Call {
	return &Rows_Scan_Call{Call: _e.mock.On("Scan",
		append([]interface{}{}, dest...)...)}
}

func (_c *Rows_Scan_Call) Run(run func(dest ...interface{})) *Rows_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Rows_Scan_Call) Return(_a0 error) *Rows_Scan_Call {
	_c.Call.Return(_a0)
	return _c
}

// Values provides a mock function with given fields:
func (_m *Rows) Values() ([]interface{}, error) {
	ret := _m.Called()

	var r0 []interface{}
	if rf, ok := ret.Get(0).(func() []interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Rows_Values_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Values'
type Rows_Values_Call struct {
	*mock.Call
}

// Values is a helper method to define mock.On call
func (_e *Rows_Expecter) Values() *Rows_Values_Call {
	return &Rows_Values_Call{Call: _e.mock.On("Values")}
}

func (_c *Rows_Values_Call) Run(run func()) *Rows_Values_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Rows_Values_Call) Return(_a0 []interface{}, _a1 error) *Rows_Values_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewRows interface {
	mock.TestingT
	Cleanup(func())
}

// NewRows creates a new instance of Rows. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRows(t mockConstructorTestingTNewRows) *Rows {
	mock := &Rows{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
