// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
)

// TimeValuer is an autogenerated mock type for the TimeValuer type
type TimeValuer struct {
	mock.Mock
}

type TimeValuer_Expecter struct {
	mock *mock.Mock
}

func (_m *TimeValuer) EXPECT() *TimeValuer_Expecter {
	return &TimeValuer_Expecter{mock: &_m.Mock}
}

// TimeValue provides a mock function with given fields:
func (_m *TimeValuer) TimeValue() (pgtype.Time, error) {
	ret := _m.Called()

	var r0 pgtype.Time
	if rf, ok := ret.Get(0).(func() pgtype.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(pgtype.Time)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimeValuer_TimeValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TimeValue'
type TimeValuer_TimeValue_Call struct {
	*mock.Call
}

// TimeValue is a helper method to define mock.On call
func (_e *TimeValuer_Expecter) TimeValue() *TimeValuer_TimeValue_Call {
	return &TimeValuer_TimeValue_Call{Call: _e.mock.On("TimeValue")}
}

func (_c *TimeValuer_TimeValue_Call) Run(run func()) *TimeValuer_TimeValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TimeValuer_TimeValue_Call) Return(_a0 pgtype.Time, _a1 error) *TimeValuer_TimeValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewTimeValuer interface {
	mock.TestingT
	Cleanup(func())
}

// NewTimeValuer creates a new instance of TimeValuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTimeValuer(t mockConstructorTestingTNewTimeValuer) *TimeValuer {
	mock := &TimeValuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
