// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
)

// TimestamptzValuer is an autogenerated mock type for the TimestamptzValuer type
type TimestamptzValuer struct {
	mock.Mock
}

type TimestamptzValuer_Expecter struct {
	mock *mock.Mock
}

func (_m *TimestamptzValuer) EXPECT() *TimestamptzValuer_Expecter {
	return &TimestamptzValuer_Expecter{mock: &_m.Mock}
}

// TimestamptzValue provides a mock function with given fields:
func (_m *TimestamptzValuer) TimestamptzValue() (pgtype.Timestamptz, error) {
	ret := _m.Called()

	var r0 pgtype.Timestamptz
	if rf, ok := ret.Get(0).(func() pgtype.Timestamptz); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(pgtype.Timestamptz)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TimestamptzValuer_TimestamptzValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TimestamptzValue'
type TimestamptzValuer_TimestamptzValue_Call struct {
	*mock.Call
}

// TimestamptzValue is a helper method to define mock.On call
func (_e *TimestamptzValuer_Expecter) TimestamptzValue() *TimestamptzValuer_TimestamptzValue_Call {
	return &TimestamptzValuer_TimestamptzValue_Call{Call: _e.mock.On("TimestamptzValue")}
}

func (_c *TimestamptzValuer_TimestamptzValue_Call) Run(run func()) *TimestamptzValuer_TimestamptzValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TimestamptzValuer_TimestamptzValue_Call) Return(_a0 pgtype.Timestamptz, _a1 error) *TimestamptzValuer_TimestamptzValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewTimestamptzValuer interface {
	mock.TestingT
	Cleanup(func())
}

// NewTimestamptzValuer creates a new instance of TimestamptzValuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTimestamptzValuer(t mockConstructorTestingTNewTimestamptzValuer) *TimestamptzValuer {
	mock := &TimestamptzValuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
