// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
)

// UUIDScanner is an autogenerated mock type for the UUIDScanner type
type UUIDScanner struct {
	mock.Mock
}

type UUIDScanner_Expecter struct {
	mock *mock.Mock
}

func (_m *UUIDScanner) EXPECT() *UUIDScanner_Expecter {
	return &UUIDScanner_Expecter{mock: &_m.Mock}
}

// ScanUUID provides a mock function with given fields: v
func (_m *UUIDScanner) ScanUUID(v pgtype.UUID) error {
	ret := _m.Called(v)

	var r0 error
	if rf, ok := ret.Get(0).(func(pgtype.UUID) error); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UUIDScanner_ScanUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanUUID'
type UUIDScanner_ScanUUID_Call struct {
	*mock.Call
}

// ScanUUID is a helper method to define mock.On call
//   - v pgtype.UUID
func (_e *UUIDScanner_Expecter) ScanUUID(v interface{}) *UUIDScanner_ScanUUID_Call {
	return &UUIDScanner_ScanUUID_Call{Call: _e.mock.On("ScanUUID", v)}
}

func (_c *UUIDScanner_ScanUUID_Call) Run(run func(v pgtype.UUID)) *UUIDScanner_ScanUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pgtype.UUID))
	})
	return _c
}

func (_c *UUIDScanner_ScanUUID_Call) Return(_a0 error) *UUIDScanner_ScanUUID_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewUUIDScanner interface {
	mock.TestingT
	Cleanup(func())
}

// NewUUIDScanner creates a new instance of UUIDScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUUIDScanner(t mockConstructorTestingTNewUUIDScanner) *UUIDScanner {
	mock := &UUIDScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
