// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Noodle
//
//	Noodle
//	Schemes:
//	  http
//	Host: localhost:8081
//	BasePath: /api
//	Version: 2.0
//	License: Apache License https://gitea.winters.org.nz/mathew/noodle/src/branch/master/LICENSE
//	Contact: Source Code https://gitea.winters.org.nz/mathew/noodle
//
//	Consumes:
//	  - application/json
//	  - multipart/form-data
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
