// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserSession user session
//
// swagger:model user_session
type UserSession struct {

	// expires
	// Format: date-time
	Expires strfmt.DateTime `json:"Expires,omitempty"`

	// Id
	ID int64 `json:"Id,omitempty"`

	// issued
	// Format: date-time
	Issued strfmt.DateTime `json:"Issued,omitempty"`

	// token
	Token string `json:"Token,omitempty"`

	// user Id
	UserID int64 `json:"UserId,omitempty"`
}

// Validate validates this user session
func (m *UserSession) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExpires(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIssued(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserSession) validateExpires(formats strfmt.Registry) error {
	if swag.IsZero(m.Expires) { // not required
		return nil
	}

	if err := validate.FormatOf("Expires", "body", "date-time", m.Expires.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *UserSession) validateIssued(formats strfmt.Registry) error {
	if swag.IsZero(m.Issued) { // not required
		return nil
	}

	if err := validate.FormatOf("Issued", "body", "date-time", m.Issued.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this user session based on context it is used
func (m *UserSession) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserSession) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserSession) UnmarshalBinary(b []byte) error {
	var res UserSession
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
