// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UsersApplicationItem users application item
//
// swagger:model users_application_item
type UsersApplicationItem struct {

	// application
	Application *Application `json:"Application,omitempty"`

	// display order
	DisplayOrder int64 `json:"DisplayOrder,omitempty"`

	// tab Id
	TabID int64 `json:"TabId,omitempty"`
}

// Validate validates this users application item
func (m *UsersApplicationItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateApplication(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UsersApplicationItem) validateApplication(formats strfmt.Registry) error {
	if swag.IsZero(m.Application) { // not required
		return nil
	}

	if m.Application != nil {
		if err := m.Application.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Application")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Application")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this users application item based on the context it is used
func (m *UsersApplicationItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateApplication(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UsersApplicationItem) contextValidateApplication(ctx context.Context, formats strfmt.Registry) error {

	if m.Application != nil {
		if err := m.Application.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Application")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Application")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UsersApplicationItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UsersApplicationItem) UnmarshalBinary(b []byte) error {
	var res UsersApplicationItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
