// Code generated by go-swagger; DO NOT EDIT.

package noodle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/mwinters-stuff/noodle/server/models"
)

// DeleteNoodleUsersHandlerFunc turns a function with the right signature into a delete noodle users handler
type DeleteNoodleUsersHandlerFunc func(DeleteNoodleUsersParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteNoodleUsersHandlerFunc) Handle(params DeleteNoodleUsersParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteNoodleUsersHandler interface for that can handle valid delete noodle users params
type DeleteNoodleUsersHandler interface {
	Handle(DeleteNoodleUsersParams, *models.Principal) middleware.Responder
}

// NewDeleteNoodleUsers creates a new http.Handler for the delete noodle users operation
func NewDeleteNoodleUsers(ctx *middleware.Context, handler DeleteNoodleUsersHandler) *DeleteNoodleUsers {
	return &DeleteNoodleUsers{Context: ctx, Handler: handler}
}

/*
	DeleteNoodleUsers swagger:route DELETE /noodle/users noodle deleteNoodleUsers

Deletes the user
*/
type DeleteNoodleUsers struct {
	Context *middleware.Context
	Handler DeleteNoodleUsersHandler
}

func (o *DeleteNoodleUsers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteNoodleUsersParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
