on: ["push"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:

    - uses: actions/checkout@v1

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: generate coverage and test results
      run: |
        go get github.com/vektra/mockery/v2@latest
        go install github.com/jstemmer/go-junit-report
        go install github.com/jandelgado/gcov2lcov@latest
        ./run-tests.sh


    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: ./coverage.lcov
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: "report.xml"
