on: ["push"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:

    - uses: actions/checkout@v1

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: generate coverage and test results
      run: |
        go get github.com/jstemmer/go-junit-report
        go get github.com/jandelgado/gcov2lcov@latest
        go get github.com/vektra/mockery/v2@latest
        go install github.com/jstemmer/go-junit-report
        go install github.com/jandelgado/gcov2lcov@latest
        ./run-tests.sh
        # cd noodlewebclient
        # ./run-tests.sh


    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: ./coverage.lcov
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    # - name: Coveralls - DART
    #   uses: coverallsapp/github-action@master
    #   with:
    #     base-path: noodlewebclient
    #     # path-to-lcov: ./coverage.lcov
    #     github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Test Results
      id: test-results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: "report.xml"

    - name: Set badge color
      shell: bash
      run: |
        case ${{ fromJSON( steps.test-results.outputs.json ).conclusion }} in
          success)
            echo "BADGE_COLOR=31c653" >> $GITHUB_ENV
            ;;
          failure)
            echo "BADGE_COLOR=800000" >> $GITHUB_ENV
            ;;
          neutral)
            echo "BADGE_COLOR=696969" >> $GITHUB_ENV
            ;;
        esac

    - name: Create badge
      uses: emibcn/badge-action@d6f51ff11b5c3382b3b88689ae2d6db22d9737d1
      with:
        label: Tests
        status: '${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.tests }} tests, ${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.runs }} runs: ${{ fromJSON( steps.test-results.outputs.json ).conclusion }}'
        color: ${{ env.BADGE_COLOR }}
        path: badge.svg

    - name: Upload badge to Gist
      # Upload only for master branch
      if: >
        github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'master' ||
        github.event_name != 'workflow_run' && github.ref == 'refs/heads/master'
      uses: andymckay/append-gist-action@1fbfbbce708a39bd45846f0955ed5521f2099c6d
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gistURL: https://gist.githubusercontent.com/mwinters-stuff/d1005a86d51b60f6f0ba92b130f77126
        file: badge.svg
