// Code generated by go-swagger; DO NOT EDIT.

package noodle_auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostAuthAuthenticateHandlerFunc turns a function with the right signature into a post auth authenticate handler
type PostAuthAuthenticateHandlerFunc func(PostAuthAuthenticateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAuthAuthenticateHandlerFunc) Handle(params PostAuthAuthenticateParams) middleware.Responder {
	return fn(params)
}

// PostAuthAuthenticateHandler interface for that can handle valid post auth authenticate params
type PostAuthAuthenticateHandler interface {
	Handle(PostAuthAuthenticateParams) middleware.Responder
}

// NewPostAuthAuthenticate creates a new http.Handler for the post auth authenticate operation
func NewPostAuthAuthenticate(ctx *middleware.Context, handler PostAuthAuthenticateHandler) *PostAuthAuthenticate {
	return &PostAuthAuthenticate{Context: ctx, Handler: handler}
}

/*
	PostAuthAuthenticate swagger:route POST /auth/authenticate noodle-auth postAuthAuthenticate

Authenticates a User
*/
type PostAuthAuthenticate struct {
	Context *middleware.Context
	Handler PostAuthAuthenticateHandler
}

func (o *PostAuthAuthenticate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostAuthAuthenticateParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
